name: Gradle build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          HDSKINS_REPO_USER: ${{ secrets.HDSKINS_REPO_USER }}
          HDSKINS_REPO_PASSWORD: ${{ secrets.HDSKINS_REPO_PASSWORD }}
        run: ./gradlew build shadowJar
      - name: Upload jar
        uses: actions/upload-artifact@v1
        with:
          name: Artifacts
          path: addon-1.8/build/libs/LabyTwitch.jar